### ISSUE TITLE
Unable to get property replace of undefined or null reference

### ISSUE THREAD

**Issue by jmsims2** [thuld/CrmFetchKit#2]
I included the library (CrmFetchKit.Bundle.js) in my CRM instance as a web resource.  When I go to execute a query, I get the error "unable to get property replace of undefined or null reference" in line 5339.  This line seems to be giving me problems starting at 5340:

var escape = module.exports = function escape(string) {
  return string.replace(/([&"<>'])/g, function(str, item) {
            return escape.map[item];
          })

Why isn't string defined?

**Comment by thuld** [comment]
Hello Jeff, 

"string" is defines, see the parameters. 

What version of the CrmFetchKit are you using, 3.2.0? All unit-test are find. Just post you code here an I will have a look.

Daniel

**Comment by jmsims2** [comment]
Completely my fault. string was undefined because the string that I was passing in wasn't getting set properly.

Works perfectly.  Thanks!
