### ISSUE TITLE
Unable to get property '<' of undefined or null reference

### ISSUE THREAD

**Issue by jacko873** [thuld/CrmFetchKit#3]
In IE i get the Above error While in chrome i do not and it works fine 

here is the code

```currenturl = window.location.href;
    annid = currenturl.substr(currenturl.lastIndexOf('/') + 1);
    annid = annid.replace("med_announcement_view?data=","");
    console.log(annid);

    var serverUrl = Xrm.Page.context.getClientUrl();
    annUrl = serverUrl + "/WebResources/med_announcement_view?data=";

 	//Announcement   
	var fetchxml = [
        '<fetch distinct="false" mapping="logical" output-format="xml-platform" version="1.0" >',
        '  <entity name="med_announcement" >',
        '    <attribute name="med_announcementid" />',
        '    <attribute name="med_name" />',
        '    <attribute name="createdon" />',
        '    <attribute name="med_shortdescription" />',
        '    <attribute name="createdby" />',
        '    <attribute name="med_announcementcontent" />',        
        '    <order descending="false" attribute="med_startedate" />',
        '    <filter>',
        '      <condition attribute="med_announcementid" value="' + annid + '" operator="eq" />',
        '    </filter>',
        '  </entity>',
        '</fetch>'
    ].join('');


    CrmFetchKit.Fetch(fetchxml).then(function(entities) {

            document.getElementById("currenttitle").innerHTML = entities[0]["attributes"]["med_name"]["value"];            
        
    });```

this is a webresource page thats **not** part of a bigger form, its a pop out page,

hence i include the below in the header so i can use the XRM object
``` <script src="ClientGlobalContext.js.aspx" type="text/javascript"></script>```

**Comment by thuld** [comment]
What version of the CrmFetchkit are you using? Where is the error thrown? When using the IE developers tools does the debugger stops in the line where the error is thrown? 

Could you upload an screen-shot that shows the error in the developer console of your browser. 

When you set an break-point on the "CrmFetchKit.Fetch(fetchxml).then(function(entities) {" line and step through you code, could you send show me the screen-shot of the line where the error is generated?

**Comment by thuld** [comment]
Hey jacko,

any feedback from your side?

**Comment by jacko873** [comment]
Apologies for the delay I have be away on holiday.
I was using 3.2, I just tried 3.3 I get the same result,
I changed from your minified version to your normal full fat version and the error changes,


![screenshot 210](https://cloud.githubusercontent.com/assets/65207/9958748/43804978-5e0d-11e5-98e3-3daa8e3e949e.jpg)
## CRM fetch is undefined 
![screenshot 211](https://cloud.githubusercontent.com/assets/65207/9958762/571ce770-5e0d-11e5-84a0-70d269bed9f9.jpg)



![screenshot 214](https://cloud.githubusercontent.com/assets/65207/9958724/153e033e-5e0d-11e5-8cbf-b4f3c189124d.jpg)

## Expected Identifier

![screenshot 215](https://cloud.githubusercontent.com/assets/65207/9958720/0bfec43e-5e0d-11e5-84ea-e4129d3c377a.jpg)

### In Chrome no error still works ok
![screenshot 213](https://cloud.githubusercontent.com/assets/65207/9958810/c473cfaa-5e0d-11e5-8616-10f6e2c2a793.jpg)

**Comment by jacko873** [comment]
Also with 3.3 i get the same error,

![screenshot 218](https://cloud.githubusercontent.com/assets/65207/9959583/62cc2b28-5e15-11e5-9218-d71304b121a9.jpg)
![screenshot 217](https://cloud.githubusercontent.com/assets/65207/9959586/645a00d2-5e15-11e5-81b8-9b704ef3bd8a.jpg)

**Comment by jacko873** [comment]
I found the issue, my IE was showing all intranet sites in ie 7 mode 

I added the `<meta http-equiv="X-UA-Compatible" content="IE=Edge">` and now it is working fine,

I tried the other modes it works in 8 and above

**Comment by thuld** [comment]
Ok, I will close this issue
