### ISSUE TITLE
Cancelling/Ignoring a fetch

### ISSUE THREAD

**Issue by filcole** [thuld/CrmFetchKit#5]
Hi,

Thanks for the great library.  Is it possible to cancel a fetch?  

Say there's a custom search form that fires off a few fetches upon pressing the "find" button.  If the find button is pressed quickly multiple times can any previous incomplete fetches that are still running be cancelled, just leaving the last search criteria running.  Is this doable?

**Comment by thuld** [comment]
Take a look at the bluebird docu: https://github.com/petkaantonov/bluebird/blob/master/API.md#cancellation

**Comment by filcole** [comment]
Thanks.  I managed to get it working after a good head scratch.
