### ISSUE TITLE
Release 3.3.0 has 3.2.0 in the body of the script

### ISSUE THREAD

**Issue by filcole** [thuld/CrmFetchKit#6]
Just thought I'd let you know that version 3.3.0 actually has version 3.2.0 at the top of the scripts:

```javascript
-// CrmFetchKit.js 3.1.0
+// crmfetchkit.js 3.2.0
 // https://github.com/thuld/CrmFetchKit

**Comment by thuld** [comment]
Thanks, I updated the release 3.3.0 and the version number is not correct in the build* files
