### ISSUE TITLE
JavaScript warnings in CRM 2015 Update 1

### ISSUE THREAD

**Issue by filcole** [thuld/CrmFetchKit#7]
There's a few JavaScript warnings appearing when using CRM 2015 Update 1.  I've fixed these in our branch with the following.  Is this patch OK?

```javascript
@@ -5602,10 +5602,13 @@
             // since version SDK 5.0.13
             url = context.getClientUrl();
         }
-        else if ( context.isOutlookClient() && !context.isOutlookOnline() ) {
+        else if ( context.isOutlookClient !== undefined && context.isOutlookOnline !== undefined &&
+                  context.isOutlookClient() && !context.isOutlookOnline() ) {
+            // isOutlookClient() and isOutlookOnline() have been depreciated in CRM 2015 Update 1
             url = localServerUrl;
         }
-        else {
+        else if ( context.getServerUrl !== undefined ) {
+            // getServerUrl() is only available pre CRM 2015 Update 1
             url = context.getServerUrl();
             url = url.replace(/^(http|https):\/\/([_a-zA-Z0-9\-\.]+)(:([0-9]{1,5}))?/, localServerUrl );
             url = url.replace(/\/$/, "" );

**Comment by thuld** [comment]
Have you executed the integration tests with this update source code?

**Comment by filcole** [comment]
Hi Daniel,
Nope.  I haven't setup a full environment

On 21 September 2015 at 15:31, Daniel Thul <notifications@github.com> wrote:

> Have you executed the integration tests with this update source code?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/thuld/CrmFetchKit/issues/7#issuecomment-141999661>.
>



-- 
Phil

**Comment by thuld** [comment]
Hello filcole, I committed some code, the method "getServerUrl" handles the logic a bit better. Right now I do not have an CRM 2013 instance running, but in my Dynamics CRM 2015 Update 1 environment are all integration tests good.
