### ISSUE TITLE
How to make result privilege different?

### ISSUE THREAD

**Issue by KingRider** [thuld/CrmFetchKit#9]
Hello

how to make result with admin to list result to member (normal) view ? is possible? privilege

Look a error:
http://prntscr.com/9aauaz

Thanks

Live:sandro.alvares

**Comment by thuld** [comment]
Hello Sandro,

I do not fully understand your question. Bases on your screen-shot has the under not the needs read permission.

In case you ask how to perform the query with the permission of an other user: This is not possible.

Daniel

Von meinem Windows Phone gesendet
________________________________
Von: Sandro Alvares<mailto:notifications@github.com>
Gesendet: ‎04.‎12.‎2015 17:52
An: thuld/CrmFetchKit<mailto:CrmFetchKit@noreply.github.com>
Betreff: [CrmFetchKit] How to make result privilege different? (#9)

Hello

how to make result with admin to list result to member (normal) view ? is possible? privilege

Look a error:
http://prntscr.com/9aauaz

Thanks

Live:sandro.alvares

---
Reply to this email directly or view it on GitHub:
https://github.com/thuld/CrmFetchKit/issues/9

**Comment by PiotrKalwasinski** [comment]
Hi Sandro,

In order to run query CRM as an elevated user you need to have a bespoke
backend solution (plugin or workflow) which then you can execute for a
given system event under specific credentials, including admin service
account.

It is not possible to bypass system security model via web service queries,
you always impersonate current user.

Thanks,
Piotr

**Comment by KingRider** [comment]
sorry brother, bad english!

So i know is not work! Its crm just xml, odata and wsdl are impossible are self member, i was thinking make crm with api from server, account token with admin to return value a resource web

Im try soap php are hard wsdl

:+1: thanks! :-/

**Comment by thuld** [comment]
Problem seems to be solved.
